### ISSUE TITLE
[NERSC] OMP Error

### ISSUE THREAD

**Issue by humnaawan** [LSSTDESC/desc-help#23]
I am not able to run multiprocessing on jupyterlab or on an interactive node; the code was running just fine before but I haven't been able to run it for the past 48 hours.

Choose all applicable topics by placing an 'X' between the [ ]:
- [x] jupyter
- [x] Cori interactive command line
- [ ] Batch jobs
- [x] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**
I can point to my script but the error appears to be from running emcee with Pool, e.g. with 100 walkers for the burn-in, I get the following error:
```
## burning in ... 
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/multiprocessing/pool.py", line 412, in _handle_workers
    pool._maintain_pool()
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/multiprocessing/pool.py", line 248, in _maintain_pool
    self._repopulate_pool()
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
```

I'd really appreciate some help.

**Comment by heather999** [comment]
Hi @humnaawan  I need a script to reproduce this so I can try it out. What I do know, is there was an jupyter upgrade at NERSC on Thursday which added "Cori2" as mentioned on the jupyter.nersc.gov login:

What is the "Cori2" option?
Click the "Cori2" button if you are willing to give JupyterLab 2.1 a test drive on the Cori shared CPU nodes.
JupyterLab 1.2 is still the default for Cori shared CPU nodes.
At the July maintenance, JupyterLab 2 will replace JupyterLab 1.
If you have any issues with JupyterLab 2, please let us know by ticket at https://help.nersc.gov

For now I'll assume you're still using the original Cori option in jupyter .. and this jupyter update wouldn't explain why you see the same problem in an interactive session.

**Comment by humnaawan** [comment]
@heather999 thanks so much! I was working Cori1 but I did just test my code on Cori2 but I am getting the same problem.

My actual script is [here](https://github.com/LSSTDESC/os-systematics/blob/likelihood-analysis/likelihood) but it requires a bit of setup. I created a stripped-down version of the script; attached here. When I run it on jupyterlab (cori2), I get a similar error as before:
```
(desc) awan@cori14: source /global/common/software/lsst/common/miniconda/setup_current_python.sh
(desc) awan@cori14: python test_emcee.py --debug

## inputs: {'debug': True}
Traceback (most recent call last):
  File "test_emcee.py", line 43, in <module>
    with Pool() as pool:
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

I tried running`test_emcee.py` multiple times on jupyterlab (cori2) and it did run successfully once (out of ~10 times).

Also, the test script runs fine on an interactive node:
```
awan@cori07:~: salloc -N 1 -q interactive -C haswell -t 00:10:00
salloc: Granted job allocation 32114744
salloc: Waiting for resource configuration
salloc: Nodes nid00031 are ready for job
awan@nid00031:~> source /global/common/software/lsst/common/miniconda/setup_current_python.sh
Including user python path: /global/homes/a/awan/.local/lib/python3.7/site-packages


Now using /global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/envs/desc/bin/python(desc) 
awan@nid00031:~/LSST/lsstRepos/os-systematics/likelihood-analysis> python test_emcee.py --debug

## inputs: {'debug': True}
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:16<00:00, 60.74it/s]
Multiprocessing took 16.5 seconds
```
although I get the same problem as before when I run by the non-example script on an interactive node (and now that I am thinking about it, I don't think I have ever gotten Pool to work successfully on an interactive node. Sorry for my statement about things being fine before a few days - it was only applicable to jupyterlab, not the interactive sessions).

**Comment by humnaawan** [comment]
oh sorry, apparently i cannot attach a .py file. here's the content:

```
# test_emcee.py
import os
import numpy as np
import emcee

import time
from multiprocessing import Pool, cpu_count

# ------------------------------------------------------------------------------
# this script test emcee multiprocessing
# following https://emcee.readthedocs.io/en/stable/tutorials/parallel/
# ------------------------------------------------------------------------------

from optparse import OptionParser
parser = OptionParser()
parser.add_option('--debug',
                  action='store_true', dest='debug', default=False,
                  help='Test code with a small chain.')
# ------------------------------------------------------------------------------
(options, args) = parser.parse_args()
print('\n## inputs: %s' % options)
# read in the inputs
debug = options.debug
# ------------------------------------------------------------------------------
start_time = time.time()
# set up log-prob
def log_prob(theta):
    t = time.time() + np.random.uniform(0.005, 0.008)
    while True:
        if time.time() >= t:
            break
    return -0.5 * np.sum(theta ** 2)

# initalize
np.random.seed(42)
if debug:
    initial = np.random.randn(32, 5)
else:
    initial = np.random.randn(1000, 5)
nwalkers, ndim = initial.shape
nsteps = 1000

# start the parallel runs
with Pool() as pool:
    sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob, pool=pool)
    start = time.time()
    sampler.run_mcmc(initial, nsteps, progress=True)
    end = time.time()
    multi_time = end - start
    print("Multiprocessing took {0:.1f} seconds".format(multi_time))
```

**Comment by humnaawan** [comment]
okay i added `os.environ["OMP_NUM_THREADS"] = "1"` to my script (following the note re NumPy parallelization in the [emcee documentation](https://emcee.readthedocs.io/en/stable/tutorials/parallel/) ) and I am now able to run things both on Jupyterlab (Cori2) and an interactive node; I get the same error as before when I remove the addition.

**Comment by heather999** [comment]
Hi @humnaawan It sounds like you found the solution!

**Comment by humnaawan** [comment]
yes, i think so. i'll close this issue. thanks so much!
