### ISSUE TITLE
[NERSC] How do I get SLURM and python-desc-bleed to work together

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/desc-help#27]
**Description**
A clear and concise description of what the issue is.  

Trying to use `dask_jobqueue` in a JupyterHub Notebook running `python-desc-bleed`, I run into the problem that the SLURM commands aren't in `python-desc-bleed`:

```
from dask_jobqueue import SLURMCluster
cluster = SLURMCluster()
cluster.scale(jobs=1)
```

gives

```
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /usr/local/py3.7/envs/desc/lib/python3.7/asyncio/tasks.py:623> exception=FileNotFoundError(2, "No such file or directory: 'sbatch'")>
Traceback (most recent call last):
  File "/usr/local/py3.7/envs/desc/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/usr/local/py3.7/envs/desc/lib/python3.7/site-packages/distributed/deploy/spec.py", line 50, in _
    await self.start()
  File "/usr/local/py3.7/envs/desc/lib/python3.7/site-packages/dask_jobqueue/core.py", line 310, in start
    out = await self._submit_job(fn)
  File "/usr/local/py3.7/envs/desc/lib/python3.7/site-packages/dask_jobqueue/core.py", line 293, in _submit_job
    return self._call(shlex.split(self.submit_command) + [script_filename])
  File "/usr/local/py3.7/envs/desc/lib/python3.7/site-packages/dask_jobqueue/core.py", line 381, in _call
    cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs
  File "/usr/local/py3.7/envs/desc/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/py3.7/envs/desc/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sbatch': 'sbatch'
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x2aaae0911f50>>, <Task finished coro=<SpecCluster._correct_state_internal() done, defined at /usr/local/py3.7/envs/desc/lib/python3.7/site-packages/distributed/deploy/spec.py:300> exception=FileNotFoundError(2, "No such file or directory: 'sbatch'")>)
Traceback (most recent call last):
  File "/usr/local/py3.7/envs/desc/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/usr/local/py3.7/envs/desc/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/usr/local/py3.7/envs/desc/lib/python3.7/site-packages/distributed/deploy/spec.py", line 335, in _correct_state_internal
    await w  # for tornado gen.coroutine support
  File "/usr/local/py3.7/envs/desc/lib/python3.7/site-packages/distributed/deploy/spec.py", line 50, in _
    await self.start()
  File "/usr/local/py3.7/envs/desc/lib/python3.7/site-packages/dask_jobqueue/core.py", line 310, in start
    out = await self._submit_job(fn)
  File "/usr/local/py3.7/envs/desc/lib/python3.7/site-packages/dask_jobqueue/core.py", line 293, in _submit_job
    return self._call(shlex.split(self.submit_command) + [script_filename])
  File "/usr/local/py3.7/envs/desc/lib/python3.7/site-packages/dask_jobqueue/core.py", line 381, in _call
    cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs
  File "/usr/local/py3.7/envs/desc/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/py3.7/envs/desc/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sbatch': 'sbatch'
```

Choose all applicable topics by placing an 'X' between the [ ]:
- [X] jupyter
- [ ] Cori interactive command line
- [X] Batch jobs
- [X] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by wmwv** [comment]
From the `salloc+srun` side, I want to do launch salloc with the `desc-python-bleed` environment, but then I can't run `srun`.

**Comment by wmwv** [comment]
Is the answer to put the SLURM commands into `desc-python-bleed`, or Yet Another Kernel Environment (tm)?

**Comment by wmwv** [comment]
Or is there a way to correctlycall `salloc`/`sbatch` 
load the `lsstdesc/desc-python:bleed` Shifter image
load the `/global/common/software/lsst/common/miniconda/kernels/python-bleed.sh` environment
and run `dask-mpi`?

**Comment by wmwv** [comment]
I'd like to be able to run something like the following:

**Comment by wmwv** [comment]
```
salloc \
    -N 1 \
    -n 16 \
    -c 4 \
    --time 04:00:00 \
    -C haswell \
    -q interactive \
    --image=lsstdesc/desc-python:bleed \
    srun -u \
        --chdir ${SCRATCH}/tmp \
        shifter \
            --image=lsstdesc/desc-python:bleed \
            -- \
              /global/common/software/lsst/common/miniconda/kernels/python-bleed.sh \
                  /usr/local/py3.7/envs/desc/bin/dask-mpi \
                    --scheduler-file=${SCRATCH}/scheduler.json \
                    --dashboard-address=0 \
                    --nthreads=1 \
                    --memory-limit=0 \
                    --no-nanny \
                    --local-directory=/tmp
```

**Comment by wmwv** [comment]
This doesn't actually work because that's not exactly what the `python-bleed.sh` kernel script does (because it's a script to provide a kernel to Jupyter).

But if you imagine it instead set the environment and then ran the command, the above is conceptually the Steps 1-4 I describe above.

**Comment by heather999** [comment]
Ultimately, I probably need to open a NERSC ticket to inquire for more details and hints.  But I do have some resources to try to figure out what to do.
There is a NERSC gitlab repo dedicated to dask, this example uses dask-mpi in a shifter image, which is started using a Jupyter terminal: https://gitlab.com/NERSC/nersc-notebooks/-/blob/master/dask/10-nersc-dask-example-cluster-start.ipynb
It may be that I need to modify the shifter image so you can avoid some of that additional set up to get the environment going so you can access dask-mpi.

NERSC has had a series of discussions, including one on Jupyter June 3rd.  If you peek at the [video](https://drive.google.com/file/d/1N73_Wn9vkqQFgasu1CWrHJAiwe7F8_Z6/view?usp=sharing) and move to about minute 22, there is an example using dask_jobqueue which I tried to reproduce using the desc-python-bleed kernel, and this worked.. but I suspect that cluster doesn't enable the same desc-python-bleed environment

```
import dask
import dask_jobqueue
from dask.distributed import Client

cluster = dask_jobqueue.SLURMCluster(
                processes = 1,
                cores = 4, 
                project="m1727",
                memory='4 GB',
                walltime="10:00",
                job_extra = ['--constraint=haswell', '--spread-job'],
                scheduler_options = {"dashboard_address":"localhost:0"}
)

print(cluster.job_script())
```

**Comment by wmwv** [comment]
Thanks.  I've read most of what NERSC has posted about Dask on NERSC, but you hit the nail on the head:

>  I suspect that cluster doesn't enable the same desc-python-bleed environment

**Comment by wmwv** [comment]
> It may be that I need to modify the shifter image so you can avoid some of that additional set up to get the environment going so you can access dask-mpi.

That sounds like a promising approach.  Thanks.

**Comment by wmwv** [comment]
Indeed, the following works, but it doesn't actually run anything.  It just defines the job script.

```
import dask
import dask_jobqueue
from dask.distributed import Client

cluster = dask_jobqueue.SLURMCluster(
                processes = 1,
                cores = 4, 
                project="m1727",
                memory='4 GB',
                walltime="10:00",
                job_extra = ['--constraint=haswell', '--spread-job'],
                scheduler_options = {"dashboard_address":"localhost:0"}
)

print(cluster.job_script())
```

If you then try to use this job script to create a worker:

```
cluster.scale(jobs=1)
```

You get the same error as reported in the initial part of this ticket.

**Comment by heather999** [comment]
Hi @wmwv Didn't forget about this..  I created an updated image for us to try out.  `lsstdesc/desc-python:bleed-dev`  which includes a start up script to set up the environment.  To get it to start up correctly at the cori command line I need to do:
`shifter --image=lsstdesc/desc-python:bleed-dev --entrypoint bash`
I can make this easier, but I'm hoping this will work for now.   I need to sort out a quote issue on my account - but I'm hoping you can give this whirl if it's a priority for you.  I'll give it a try once I can access the interactive queue again!

**Comment by wmwv** [comment]
I get

```
[nid00046 ~] shifter --image=lsstdesc/desc-python:bleed-dev --entrypoint bash
bash-4.2$ which python
/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/bin/python
```

Instead of the `/usr/local/py3.7/envs/desc/bin/python` that I should get from the `desc-python-bleed` environment.

Am I misunderstanding something about how I should be trying this out?

**Comment by heather999** [comment]
hmm.. I'm not sure what is different.  At first I was wondering if it was an issue with compute versus interactive nodes.  This is what I do:
```
heatherk@cori07:~> salloc -C haswell -N 1 -q interactive -t 01:00:00 -L SCRATCH
salloc: Pending job allocation 32563137
salloc: job 32563137 queued and waiting for resources
salloc: job 32563137 has been allocated resources
salloc: Granted job allocation 32563137
salloc: Waiting for resource configuration
salloc: Nodes nid00281 are ready for job
heatherk@nid00281:~> shifter --image=lsstdesc/desc-python:bleed-dev --entrypoint bash
bash-4.2$ which conda
/usr/local/py3.7/condabin/conda
bash-4.2$ which python
/usr/local/py3.7/envs/desc/bin/python
```

Similarly if I start up a jupyter terminal I see:
```
heatherk@cori16:/global/u1/h/heatherk> shifter --image=lsstdesc/desc-python:bleed-dev --entrypoint bash
bash-4.2$ which conda
/usr/local/py3.7/condabin/conda
bash-4.2$ 
```

Can you give me the steps to reproduce exactly how you get that result?

**Comment by wmwv** [comment]
```
[cori03 ~] salloc -C haswell -N 1 -q interactive -t 01:00:00 -L SCRATCH
salloc: Pending job allocation 32563382
salloc: job 32563382 queued and waiting for resources
salloc: job 32563382 has been allocated resources
salloc: Granted job allocation 32563382
salloc: Waiting for resource configuration
salloc: Nodes nid00053 are ready for job
[nid00053 ~] shifter --image=lsstdesc/desc-python:bleed-dev --entrypoint bash
bash-4.2$ which python
/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/bin/python
```

**Comment by wmwv** [comment]
So running the same thing as you gets me a different result.

Perhaps there's something in my *PATH variables that shouldn't be set?

**Comment by heather999** [comment]
Yes- that's a good idea.. it must be something different in our environments.  I keep things very vanilla in my .bashrc so I can reproduce issues (at the expense of convenience!) :)  I would poke around your PATH and see what's in your .bashrc that might be causing this.. I'd also check the modules you have loaded, that looks like NERSC's `python3/3.7-anaconda-2019.10`  So maybe peek at `module list` to see what's being loaded.

**Comment by wmwv** [comment]
```
[cori03 ~] module list
Currently Loaded Modulefiles:
  1) modules/3.2.11.4                                 13) xpmem/2.2.20-7.0.1.1_4.10__g0475745.ari
  2) altd/2.0                                         14) job/2.2.4-7.0.1.1_3.36__g36b56f4.ari
  3) darshan/3.1.7                                    15) dvs/2.12_2.2.156-7.0.1.1_8.9__g5aab709e
  4) intel/19.0.3.199                                 16) alps/6.6.58-7.0.1.1_6.4__g437d88db.ari
  5) craype-network-aries                             17) rca/2.2.20-7.0.1.1_4.46__g8e3fb5b.ari
  6) craype/2.6.2                                     18) atp/2.1.3
  7) cray-libsci/19.06.1                              19) PrgEnv-intel/6.0.5
  8) udreg/2.3.2-7.0.1.1_3.31__g8175d3d.ari           20) craype-haswell
  9) ugni/6.0.14.0-7.0.1.1_7.33__ge78e5b0.ari         21) cray-mpich/7.7.10
 10) pmi/5.0.14                                       22) craype-hugepages2M
 11) dmapp/7.1.1-7.0.1.1_4.48__g38cf134.ari           23) gcc/8.3.0
 12) gni-headers/5.0.12.0-7.0.1.1_6.28__g3b1768f.ari
```

**Comment by heather999** [comment]
Ok - not there :)  If you do `which python` at the command line just upon login - where does it point?

**Comment by heather999** [comment]
Ok - so that implies there is something in your $HOME/.bashrc or $HOME/.bashrc.ext that is setting up this version of python. But somehow it's not doing a module load...

**Comment by heather999** [comment]
But given the time and that it is almost the weekend - I would consider opening a NERSC ticket to try to figure out what is going on in your environment.  They can actually see your bashrc while I cannot.

**Comment by wmwv** [comment]
Yes, it was something my `.bashrc`.  I had tried setting up conda environments at one point, and `conda init` had dropped stuff into my `.bashrc` that was causing the default path to pick up the Python that `conda` knew about.

I've cleaned that up, and now get what you get
```
[cori10 ~] salloc     -N 1     -n 16     -c 4     --time 04:00:00     -C haswell     -q interactive     --image=lsstdesc/desc-python:bleed-dev
salloc: Granted job allocation 33366690
salloc: Waiting for resource configuration
salloc: Nodes nid00062 are ready for job
[nid00062 ~] shifter --image=lsstdesc/desc-python:bleed-dev --entrypoint bash
bash-4.2$ which python
/usr/local/py3.7/envs/desc/bin/python
```

**Comment by wmwv** [comment]
But I can't get the MPI part to work:
```
salloc \
    -N 1 \
    -n 16 \
    -c 4 \
    --time 04:00:00 \
    -C haswell \
    -q interactive \
    --image=lsstdesc/desc-python:bleed-dev \
    srun -u -n 16 \
        shifter --image=lsstdesc/desc-python:bleed-dev \
            --entrypoint \
            /usr/local/py3.7/envs/desc/bin/dask-mpi \
                --scheduler-file=${SCRATCH}/scheduler.json \
                --dashboard-address=0 \
                --nthreads=1 \
                --memory-limit=0 \
                --no-nanny \
                --local-directory=/tmp
```

gives

```
salloc: Granted job allocation 33368414
salloc: Waiting for resource configuration
salloc: Nodes nid00017 are ready for job
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00017:16652] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00017:16658] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00017:16664] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00017:16670] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00017:16676] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00017:16682] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00017:16688] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00017:16694] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00017:16700] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00017:16706] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00017:16711] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00017:16718] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00017:16724] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00017:16730] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00017:16736] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00017:16742] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
srun: error: nid00017: tasks 0-15: Exited with exit code 1
srun: Terminating job step 33368414.0
salloc: Relinquishing job allocation 33368414
```

**Comment by wmwv** [comment]
I submitted this as a NERSC ticket at
